import AppKit
import Combine

// ClipboardMonitor.swift
// An OPTIONAL clipboard history of copied TEXT.
//  - It is OFF until you switch it on and agree to the question that appears.
//  - It only runs while the switch is on; turning it off stops it immediately.
//  - It ignores items that apps mark as secret (password managers) or temporary.
//  - It keeps the list in memory only, unless you also tick "Keep after quitting".
//  - Nothing is ever sent anywhere.

struct ClipboardItem: Identifiable, Codable, Equatable {
    var id = UUID()
    var text: String
    var date = Date()
}

final class ClipboardMonitor: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []
    @Published private(set) var isRunning = false

    private let settings: AppSettings
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var cancellables = Set<AnyCancellable>()
    private static let fileName = "clipboard.json"
    private static let secretTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword")
    ]

    init(settings: AppSettings) {
        self.settings = settings
        if settings.prefs.clipboardKeepAfterQuit {
            items = LocalStore.load([ClipboardItem].self, name: Self.fileName) ?? []
        }
        settings.$prefs
            .map { $0.clipboardHistoryEnabled }
            .removeDuplicates()
            .receive(on: DispatchQueue.main)
            .sink { [weak self] enabled in enabled ? self?.start() : self?.stop() }
            .store(in: &cancellables)
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        isRunning = true
        timer = Timer.scheduledTimer(withTimeInterval: 0.8, repeats: true) { [weak self] _ in self?.poll() }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    func clear() {
        items = []
        LocalStore.remove(name: Self.fileName)
    }

    func copyAgain(_ item: ClipboardItem) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(item.text, forType: .string)
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        persistIfNeeded()
    }

    private func poll() {
        let board = NSPasteboard.general
        guard board.changeCount != lastChangeCount else { return }
        lastChangeCount = board.changeCount
        let types = board.types ?? []
        if types.contains(where: { Self.secretTypes.contains($0) }) { return }
        guard let text = board.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !text.isEmpty else { return }
        let clipped = String(text.prefix(2000))
        items.removeAll { $0.text == clipped }
        items.insert(ClipboardItem(text: clipped), at: 0)
        if items.count > 25 { items.removeLast(items.count - 25) }
        persistIfNeeded()
    }

    func persistIfNeeded() {
        if settings.prefs.clipboardKeepAfterQuit {
            LocalStore.save(items, name: Self.fileName)
        } else {
            LocalStore.remove(name: Self.fileName)
        }
    }
}
